# Base blog settings
baseurl: "" # the subpath of your site,                         # e.g. /blog/
# set to '' in case of hosting on GitHub
url:
  "https://maxkim-j.github.io" # the base hostname & protocol for your site
  # `http://<username>.github.io` - for GitHub

blog:
  title: 김맥스 기술 블로그
  short_title: 技以求道
  description: 김맥스 기술 블로그 powered By Jekyll,

  # Layout configuration
  logo_path: "" # path to logo file
  search_path:
    "maxkim-j.github.io"
    # needed for searchbox in archive page
  hero_layout: false # turn on hero layout for blog and posts
  hero_placeholder: "assets/img/generic_hero.jpg" # placeholder for hero image
  excerpts: true # show excerpts instead of full post content on blog page
  inline_footnotes: true # enable/disable barefoot inline footnotes
  titles_only: false # show post titles only on main blog page

  # Fonts
  font: '"Noto Sans KR", "Rubik", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
  load_google_fonts: "Noto Rubik:400,400italic,700,700italic"
# Author info
author:
  fullname: Max Jonghyuk Kim
  rss: false # generate RSS feed and show it's icon in header
  mail: false # change to your e-mail address
  twitter: false
  github: MaxKim-J
  youtube: false
  stackoverflow: false
  disqus: https-maxkim-j-github-io # your disqus site name
  google_analytics: UA-132859535-2
  photo: "uploads/me2.png"
  photo2x: "uploads/about.jpeg"

## !!
## Advanced blog settings
## You should not change anything here unless you know what you are doing

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Permalinks
permalink: posts/:slug

# Posts
excerpt_separator: <!–-break-–>

# Pagination
paginate: 10
paginate_path: "/page-:num/"

# Tags
collections:
  my_tags:
    output: true
    permalink: /tag/:slug
defaults:
  - scope:
      path: ""
      type: my_tags
    values:
      layout: blog-by-tag

# Handling Reading
exclude: ["README.md", "README.html"]

# https://github.com/jekyll/jekyll/issues/4619
# Markdown and highlighter settings
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)

highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  # syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: "highlight"
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sass settings
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  endings: all
  comments: ["<!-- ", " -->"]
  blanklines: true
  profile: false
  ignore:
  envs: [local]
